version: '3'

services:
  php:
    image: ngyuki/php-dev:7.0
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: test
      MYSQL_USER: root
    command: |
      php -v
    working_dir: /app
    volumes:
      - .:/app:rw

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
